FROM webdevops/php-nginx:8.3

WORKDIR /application

# Copy application files
COPY . /application

# Install composer dependencies
RUN composer install --no-interaction --no-dev --optimize-autoloader

# Set environment variables
ENV WEB_DOCUMENT_ROOT=/application/webroot
