version: '3'
services:
  psql16:
    image: postgres:16
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=my_app
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=my_app
      - PGUSER=my_app
      - PGDATABASE=my_app
      - PGPASSWORD=secret
    restart: unless-stopped

  redis:
    image: redis:7
    volumes:
      - ./redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  cakephp:
    build:
      context: .
      dockerfile: Dockerfile.cakephp
    environment:
      - DATABASE_URL=postgres://my_app:secret@psql16:5432/my_app
      - QUEUE_DEFAULT_URL=redis://redis:6379
    depends_on:
      - psql16
      - redis
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - DATABASE_URL=postgres://my_app:secret@psql16:5432/my_app
      - QUEUE_DEFAULT_URL=redis://redis:6379
    depends_on:
      - psql16
      - redis
    restart: unless-stopped

