version: '3'
services:
  psql16:
    image: postgres:16
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=my_app
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=my_app
      - PGUSER=my_app
      - PGDATABASE=my_app
      - PGPASSWORD=secret
    restart: unless-stopped

  cakephp:
    build:
      context: .
      dockerfile: Dockerfile.cakephp
    environment:
      - DATABASE_URL=postgres://my_app:secret@psql16:5432/my_app
    depends_on:
      - psql16
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - DATABASE_URL=postgres://my_app:secret@psql16:5432/my_app
    depends_on:
      - psql16
    restart: unless-stopped

