FROM webdevops/php-nginx:8.3

WORKDIR /application

# Copy application files
COPY . /application

# Install composer dependencies
RUN composer install --no-interaction --optimize-autoloader

# Copy supervisor configuration
COPY config/supervisor/worker.conf /etc/supervisor/conf.d/worker.conf
COPY config/supervisor/supervisord.conf /etc/supervisor/supervisord.conf

# Command to run syslog-ng and supervisor
CMD supervisord -c /etc/supervisor/supervisord.conf
